
import os
import argparse
from pathlib import Path
import deeplabcut
from deeplabcut import video_inference_superanimal
import pandas as pd
import glob

def main():
    parser = argparse.ArgumentParser(description="Run SuperAnimal Inference on a Folder of Images")
    parser.add_argument("--image_dir", required=True, help="Directory containing images")
    parser.add_argument("--model_name", default="superanimal_quadruped", help="SuperAnimal model name")
    parser.add_argument("--scale_list", nargs='+', type=int, default=range(200, 600, 50), help="Scale list for inference")
    parser.add_argument("--video_type", default=".jpg", help="Image extension (e.g., .jpg, .png)")
    
    args = parser.parse_args()
    
    img_dir = Path(args.image_dir).resolve()
    if not img_dir.exists():
        print(f"❌ Error: Image directory not found: {img_dir}")
        return

    print(f"Looking for images in {img_dir} with extension {args.video_type}...")
    
    # DLC's video_inference_superanimal typically expects video paths. 
    # However, some versions might support treating a folder of images as a video or list of images.
    # If not, we might need to use a different approach or trick it.
    
    # Approach 1: Try passing the directory path itself, if DLC supports "directory of images" as a video input.
    # Approach 2: Pass list of image paths.
    
    # Let's try passing the directory first as a list containing the directory, usually DLC handles folder inputs for some functions.
    # But video_inference_superanimal is high-level. 
    
    # Documentation suggests it takes `videos` (list of paths).
    # Let's try passing the list of all image paths.
    
    image_paths = sorted(list(img_dir.glob(f"*{args.video_type}")))
    
    if not image_paths:
        print(f"❌ No images found in {img_dir}")
        return
        
    print(f"Found {len(image_paths)} images. Starting inference...")
    
    # Note: treating each image as a "video" might be slow if it reloads the model each time.
    # Ideally we process them in batches. 
    # If video_inference_superanimal doesn't support list of images as a single "video" sequence,
    # we might need `deeplabcut.analyze_time_lapse_frames` equivalent.
    
    # CRITICAL: video_inference_superanimal is designed for videos. 
    # Running it on 400 images individually will be incredibly slow (model load 400 times).
    # WE MUST check if we can pass the folder or if we need to convert to a video first (which rf_to_dlc.py does!)
    
    # Wait! The user's `rf_to_dlc.py` CREATES videos from these images!
    # "Create video from each image set" -> `output_dir = base_dir / "videos"`
    # Maybe the user WANTS to run on the generated videos?
    # The request was: "run pre-inference on images like this"
    
    # If we MUST run on images directly without converting to video:
    # We should use `deeplabcut.analyze_time_lapse_frames` BUT that requires a config.
    # SuperAnimal is "zero-shot" / "model-zoo".
    
    # Let's try to use the `video_inference_superanimal` on the *directory*, DLC sometimes treats a dir of images as a video.
    try:
        # We will attempt to run on the directory itself.
        # If that fails, we might warn the user to use the videos generated by rf_to_dlc.py
        
        # Actually, let's look at `inference_pre_finetune.py`. It calls `video_inference_superanimal`.
        # If we pass a list of images, will it treat them as separate videos? Yes.
        
        # HACK: Create a temporary video from the images? 
        # OR: Use `deeplabcut.modelzoo.analyze_time_lapse_frames` if it implies superanimal support? Unlikely.
        
        # Best approach for "SuperAnimal on Images":
        # 1. Adapt the logic from `video_inference_superanimal` source (which wraps `analyze_video`).
        # 2. But `analyze_video` needs a config.
        # 3. `video_inference_superanimal` creates a temporary project/config.
        
        # Let's assume the user has videos generated by `rf_to_dlc.py` (which they do, in `dataset/videos`).
        # If they specifically asked for "images", maybe they don't have the videos yet or want to verify on raw images.
        
        # Let's try to simulate a video by treating the folder as one.
        # If that's too complex/unsupported, we fallback to pointing them to the videos.
        
        # However, checking `rf_to_dlc.py` line 109: it creates videos!
        # The user said "dataset... this is how structure is... update script... to run ... on images like this".
        # They might mean "run on the dataset which is a set of images".
        
        # Let's create a script that:
        # 1. Checks if `videos` folder exists and has content.
        # 2. If yes, runs on those videos.
        # 3. If no, OFFERS to create videos from the images (using `rf_to_dlc` logic) THEN runs inference.
        #    This is much more efficient than 400 model loads.
        
        print("\n⚠ PERFORMANCE WARNING: Running SuperAnimal on individual images is extremely slow.")
        print("It is highly recommended to convert images to a video first.")
        
        # Let's try to find if `rf_to_dlc.py` generated videos are available.
        # They should be in `dataset/videos` or `base_dir/videos`.
        
        # We will attempt to use the existing `video_inference_superanimal` on the IMAGE PATHS directly.
        # If DLC is smart, it might handle it. If not, it crashes.
        # Let's try a safe bet: We treat the directory as the input if DLC supports it.
        
        # Actually, looking at DLC docs, `analyze_time_lapse_frames` is for images.
        # But `superanimal` wrapper might not expose it.
        
        # Let's default to the method that works: 
        # Since we cannot easily "image inference" with superanimal wrapper without a config.
        # We will Update the script to:
        # 1. Accept image dir.
        # 2. Create a temporary video from these images (using ffmpeg or cv2).
        # 3. Run inference on that video.
        # 4. Extract results.
        # 5. Save as CSV.
        
        import cv2
        import numpy as np
        
        # Temp Video Creation
        temp_video_path = img_dir / "temp_inference_video.mp4"
        
        if not temp_video_path.exists():
            print("Creating temporary video from images for efficient inference...")
            img = cv2.imread(str(image_paths[0]))
            height, width, layers = img.shape
            size = (width,height)
            out = cv2.VideoWriter(str(temp_video_path), cv2.VideoWriter_fourcc(*'mp4v'), 30, size)
            
            for f in image_paths:
                out.write(cv2.imread(str(f)))
            out.release()
            print(f"Created {temp_video_path}")
        else:
            print(f"Using existing temporary video: {temp_video_path}")
            
        # Run Inference on the temp video
        video_inference_superanimal(
            [str(temp_video_path)],
            args.model_name,
            scale_list=args.scale_list,
            videotype=".mp4",
        )
        
        # Output handling
        # Find generated H5
        output_dir = img_dir
        # The H5 will be named temp_inference_videoDLC....h5
        candidates = list(output_dir.glob("temp_inference_video*superanimal*.h5"))
        
        for h5_file in candidates:
             df = pd.read_hdf(h5_file)
             
             # The frames in the video correspond 1:1 to the sorted image_paths
             # We can replace the index or add a column for "image_name" to match compare script
             
             if len(df) != len(image_paths):
                 print(f"⚠ Warning: Frame count ({len(df)}) matches image count ({len(image_paths)})?")
                 # If mismatch, we can't easily map back.
                 
             # Add image filenames
             # We assume strict ordering.
             # Slice df to match if needed (sometimes extra frame?)
             n_frames = min(len(df), len(image_paths))
             df = df.iloc[:n_frames].copy()
             image_paths_trunc = image_paths[:n_frames]
             
             # Save as CSV with original filenames if possible or just the raw DLC output
             # To make it compatible with `compare_inference_coco.py`, we need to ensure mapping is clear.
             # The compare script maps by "frame index" -> "image list sorted by frame number".
             # So a straight H5->CSV convert is sufficient IF the sort order is identical.
             
             # `image_paths` here is sorted alphabetically. 
             # `rf_to_dlc.py` sorts by frame number extracted from filename.
             # We MUST Sort `image_paths` by frame number if possible to match the video creation logic if we want consistency.
             # User's files: `..._mp4-0000_jpg...`
             # Let's try to sort by that embedded number if present.
             
             try:
                 import re
                 # Pattern from rf_to_dlc: (?P<group>.+?_mp4)-(?P<frame>\d+)_jpg
                 pattern = re.compile(r"(?P<group>.+?_mp4)-(?P<frame>\d+)_jpg")
                 def get_frame(p):
                     match = pattern.search(p.name)
                     return int(match.group("frame")) if match else -1
                 
                 image_paths.sort(key=get_frame)
             except:
                 pass # Fallback to alphabetical
             
             csv_name = h5_file.with_suffix('.csv')
             df.to_csv(csv_name)
             print(f"Saved inference results to: {csv_name}")
             
             # Cleanup temp video? Maybe keep it for debugging.
             # os.remove(str(temp_video_path))

    except Exception as e:
        print(f"❌ Error during inference: {e}")

if __name__ == "__main__":
    main()
